# Generated by Django 5.1.1 on 2024-10-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='ht_posts', to='BlogApp.hashtag'),
        ),
    ]
